# Generated by Django 2.2.5 on 2020-10-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201027_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
